### ISSUE TITLE
Not Receiving Himawari9

### ISSUE THREAD

**Issue by ZL1LAC** [JVital2013/goestools-win#5]
Not sure why I'm not receiving Him9 images, but this is all I gotten so far.
![image](https://github.com/JVital2013/goestools-win/assets/909007/20895537-b6d5-4a82-998f-00d29a473456)

Using the config from the repo and has been untouched.
```
[[handler]]
type = "image"
origin = "himawari8"
directory = "Saved/himawari9/{region:short|lower}"
filename = "Himawari9_{region:short}_{channel:short}_{time:%Y%m%dT%H%M%SZ}"
format = "jpg"
json = false

  [[handler.map]]
  path = "share/ne/ne_50m_admin_0_countries_lakes.json"

  [[handler.map]]
  path = "share/ne/ne_50m_admin_1_states_provinces_lakes.json"
```

**Comment by JVital2013** [comment]
Looks like a Windows-specific time parsing bug. See how the only images you got are dated 1970? It's failing to parse the date from the stream for some reason. It's definitely a problem with the Windows port, but I need some sample data to fix it since I can't get GOES-18.

If you're able, can you please open a command line in he `goestools-win\bin` folder, and let the following command run for at least 2 hours:

```
goeslrit.exe --subscribe tcp://127.0.0.1:5004 --all --vcid 60 --out lrit
```

It won't look like it's doing anything at first, but once Himawari data is transmittied, it will save the raw *.lrit data into a folder named LRIT. Once it saves the data for a few hours, zip it up and send it over! I'll use the data to fix this bug

**Comment by ZL1LAC** [comment]
Ok I have started, and will report back in 1 to 2 hours, let me know if it needs to be 2 hours.

**Comment by JVital2013** [comment]
I'm hoping to get 2 sets of images (hence 2 hours), but I can get away with 1 set

**Comment by ZL1LAC** [comment]
Alright I'll no problem will do.

**Comment by ZL1LAC** [comment]
Here we go.  Let me know if you need anything else or more lrit sample files.
[lrit.zip](https://github.com/JVital2013/goestools-win/files/12207337/lrit.zip)

**Comment by JVital2013** [comment]
Thanks! I can reproduce the issue with the sample LRIT files. It should be a straightforward fix (famous last words 😄)

I'll get back to you in the next day or so.

**Comment by ZL1LAC** [comment]
No problem, happy to help, and thanks for getting this project on Windows.

**Comment by JVital2013** [comment]
**Aaand it's fixed!** It came down to my shim for strptime() - the function does not exist on Windows, and my shim works slightly different than the real Linux implementation.

Pull version 1.0.6 to get the fix. Thanks again!

![image](https://github.com/JVital2013/goestools-win/assets/24253715/b9c7068a-0c26-4beb-b9bb-cd9e90c42fa9)
